name: publish-on-tag

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '*'

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
      IMAGE_NAME: ghcr.io/thorsager/mockdev

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Build image
        run: |
          docker build . --tag "${IMAGE_NAME}:${{ steps.get_tag_name.outputs.TAG }}"

      - name: Push image
        run: |
          echo ${PAT} | docker login ghcr.io -u thorsager --password-stdin
          docker push "${IMAGE_NAME}:${{ steps.get_tag_name.outputs.TAG }}"

