name: publish-on-branch

on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - '*'

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    env:
      PAT: ${{ secrets.PAT }}
      IMAGE_NAME: ghcr.io/thorsager/mockdev

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=tags::${IMAGE_NAME}:${GITHUB_REF##*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Registry Login
        run: |
          echo ${PAT} | docker login ghcr.io -u thorsager --password-stdin

      - name: Build image
        run: |
          docker build . --tag "${IMAGE_NAME}:${GITHUB_REF##*/}"

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}

